# ./appspec.yml (Corrected)
version: 0.0
os: linux
files:
  - source: / # Copy everything from the build artifact root
    destination: /var/www/photocomp-api # Destination directory on EC2
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user # Use 'ubuntu' if using Ubuntu AMI
    - location: scripts/clean_directory.sh
      timeout: 300
      runas: ec2-user # Use 'ubuntu' if using Ubuntu AMI
  AfterInstall:
    # REMOVED: scripts/set_permissions.sh hook was here - it was incorrect
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user # Use 'ubuntu' if using Ubuntu AMI
    - location: scripts/fetch_env_vars.sh
      timeout: 120
      runas: ec2-user # Use 'ubuntu' if using Ubuntu AMI
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user # Use 'ubuntu' if using Ubuntu AMI
  ValidateService:
    # KEEP THIS: This validation runs *after* the server starts
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ec2-user # Use 'ubuntu' if using Ubuntu AMI